name: Test Jupyter Notebooks

on: 
  push:
    paths:
    - 'eda-analysis.ipynb'
  pull_request:
    paths:
    - 'eda-analysis.ipynb'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nbconvert[jupyter] jupyter
        pip install -r requirements.txt
      
    - name: Execute eda-analysis.ipynb
      run: |
        jupyter nbconvert --to notebook --execute eda-analysis.ipynb --allow-errors --output eda-analysis.ipynb
  
